const ErrorCodes = Object.freeze({
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  
    UNAUTHORIZED: 'UNAUTHORIZED',
    INVALID_TOKEN: 'INVALID_TOKEN',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    FORBIDDEN: 'FORBIDDEN',
    MISSING_SCOPE: 'MISSING_SCOPE',
  
    VALIDATION_ERROR: 'VALIDATION_ERROR',
  
    PROCESS_NOT_FOUND: 'PROCESS_NOT_FOUND',
    PROCESS_ID_MISSING: 'PROCESS_ID_MISSING',
    INVALID_WORKFLOW_STATE: 'INVALID_WORKFLOW_STATE',
    UNKNOWN_WORKFLOW_ACTION: 'UNKNOWN_WORKFLOW_ACTION',
    WORKFLOW_ALREADY_COMPLETED: 'WORKFLOW_ALREADY_COMPLETED',
    WORKFLOW_IN_ERROR_STATE: 'WORKFLOW_IN_ERROR_STATE',
  
    CONSENT_REJECTED: 'CONSENT_REJECTED',
    CONSENT_MISSING: 'CONSENT_MISSING',
  
    FHIR_SERVER_UNAVAILABLE: 'FHIR_SERVER_UNAVAILABLE',
    FHIR_REQUEST_FAILED: 'FHIR_REQUEST_FAILED',
    FHIR_TRANSACTION_FAILED: 'FHIR_TRANSACTION_FAILED',
    FHIR_RESOURCE_NOT_FOUND: 'FHIR_RESOURCE_NOT_FOUND',
    FHIR_REFERENCE_MISSING: 'FHIR_REFERENCE_MISSING',
    FHIR_RESPONSE_INVALID: 'FHIR_RESPONSE_INVALID',
  
    DATABASE_CONNECTION_FAILED: 'DATABASE_CONNECTION_FAILED',
    DATABASE_OPERATION_FAILED: 'DATABASE_OPERATION_FAILED'
  });
  
  module.exports = ErrorCodes;